// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proiectASP.NET.Data;

namespace proiectASP.NET.Migrations
{
    [DbContext(typeof(ProiectContext))]
    [Migration("20220122092101_TablesAndAllRelations")]
    partial class TablesAndAllRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("proiectASP.NET.Entities.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("NrCamera")
                        .HasColumnType("int");

                    b.Property<int>("NrPersoane")
                        .HasColumnType("int");

                    b.Property<int>("SeaView")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Camere");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NrStele")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.RezervareClientHotel", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("RezervariClientHotel");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Camera", b =>
                {
                    b.HasOne("proiectASP.NET.Entities.Hotel", "Hotel")
                        .WithMany("Camere")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Manager", b =>
                {
                    b.HasOne("proiectASP.NET.Entities.Hotel", "Hotel")
                        .WithOne("Manager")
                        .HasForeignKey("proiectASP.NET.Entities.Manager", "HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.RezervareClientHotel", b =>
                {
                    b.HasOne("proiectASP.NET.Entities.Client", "Client")
                        .WithMany("RezervariClientHotel")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("proiectASP.NET.Entities.Hotel", "Hotel")
                        .WithMany("RezervariClientHotel")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Client", b =>
                {
                    b.Navigation("RezervariClientHotel");
                });

            modelBuilder.Entity("proiectASP.NET.Entities.Hotel", b =>
                {
                    b.Navigation("Camere");

                    b.Navigation("Manager");

                    b.Navigation("RezervariClientHotel");
                });
#pragma warning restore 612, 618
        }
    }
}
